workflow:
    - publish
shared:
    image: node:6
jobs:
    main:
        steps:
            - print: `echo main: test`
            - set-env: . ./set-env.sh
    publish:
        template: screwdriver-cd/semantic-release-node8
        secrets:
            - GH_TOKEN
            - NPM_TOKEN
