shared:
    image: node:6
jobs:
    main:
        requires: ~commit
        steps:
        - echo: echo hello
    publish:
        requires: main
        template: screwdriver-cd/semantic-release-node8
        secrets:
        - GH_TOKEN
        - NPM_TOKEN
