workflow:
    - publishss
shared:
    image: node:6
jobs:
    main:
        steps:
            - print: echo the main jobs started!
            - set-env: . ./set-env.sh
    publishss:
        steps:
            - set-env: . ./set-env.sh
            - get-env: echo hi $FOO
            - install: npm install semantic-release
            - publish: npm run semantic-release
            - check-version: ./check-version.sh
        secrets:
            - GH_TOKEN
            - NPM_TOKEN
